### ISSUE TITLE
Runtime validation cannot check for required and non-required keys

### ISSUE THREAD

**Issue by ksaaskil** [meeshkan/py-http-types#10]
Because of how type-checking works, it's not possible to verify in run-time that, for example, `Request` has all the required keys and, in addition to those, has a subset of non-required keys. Either one sets `total=True` for `Request` (like currently), in which case _all_ keys are required, or one sets `total=False`, in which case no keys are required at run-time. 

Decide which one's better and document that.

More details:
- https://github.com/python/mypy_extensions/issues/7
- https://github.com/agronholm/typeguard/issues/101

**Comment by mikesol** [comment]
Fixed in 0.2.8 thanks to migration to dataclasses.
